"""
Loads the cleaned Telco churn CSV into a SQLite database and executes
all business queries from churn_queries.sql, saving results to
sql/query_results.md for documentation / portfolio purposes.
"""
import sqlite3
import pandas as pd
import re

df = pd.read_csv("../data/telco_churn_cleaned.csv")
conn = sqlite3.connect("churn.db")
df.to_sql("customers", conn, if_exists="replace", index=False)
print(f"Loaded {len(df)} rows into SQLite table 'customers'.")

with open("churn_queries.sql") as f:
    sql_content = f.read()

# Split into individual queries using the "-- Q<n>." comment markers
blocks = re.split(r"(?=-- Q\d+\.)", sql_content)
results_md = ["# SQL Query Results\n", "Generated by running `churn_queries.sql` against `churn.db`.\n"]

for block in blocks:
    block = block.strip()
    if not block.startswith("-- Q"):
        continue
    header_match = re.match(r"-- (Q\d+\..*)", block)
    header = header_match.group(1) if header_match else "Query"

    # Extract the actual SQL (strip comment lines)
    sql_lines = [l for l in block.split("\n") if not l.strip().startswith("--")]
    query = "\n".join(sql_lines).strip()
    if not query:
        continue

    try:
        result_df = pd.read_sql_query(query, conn)
        results_md.append(f"\n## {header}\n")
        results_md.append(result_df.to_markdown(index=False))
        results_md.append("\n")
        print(f"\n{header}")
        print(result_df.to_string(index=False))
    except Exception as e:
        print(f"Error running query '{header}': {e}")

with open("query_results.md", "w") as f:
    f.write("\n".join(results_md))

print("\n\nAll query results saved to sql/query_results.md")
conn.close()
